### ISSUE TITLE
Bug: chezmoi-source-file: Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by gwbrck** [tuh8888/chezmoi.el#14]
After the latest update I get an error when running `chezmoi-magit-status`: "chezmoi-source-file: Wrong type argument: stringp, nil"
I am using emacs 29...

**Comment by tuh8888** [comment]
Thanks. I think that should be resolved after I merge 8706454cba84cbea5bd8675e302ff127281bbb49 into `main`.

**Comment by tuh8888** [comment]
Should be resolved now with e80c54f06af7545fa239a9fec3917376c7f12261
