### ISSUE TITLE
Inheriting mode stoped working

### ISSUE THREAD

**Issue by gwbrck** [tuh8888/chezmoi.el#15]
when using "chezmoi-find" the mode does not get inherited from target-file.

A fix that worked for me, was changing https://github.com/tuh8888/chezmoi.el/blob/0b25d312a84868d6cf76f2016cd0dbc70c9312a0/chezmoi.el#L280 to
`(let ((target-file file))`

**Comment by tuh8888** [comment]
Good catch. That's definitely a mistake. Yours works in most situations but it should really be `(let ((target-file (chezmoi-target-file file))`. I can get to it in a couple days or if you want to open a pull-request to get it sooner, feel free.
