### ISSUE TITLE
Error when running chezmoi-ediff: wrong-type-argument stringp nil

### ISSUE THREAD

**Issue by offbyone** [tuh8888/chezmoi.el#17]
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-nondirectory(nil)
  chezmoi-find("~/.local/etc/supervisord-devtools.conf")
  chezmoi-ediff("~/.local/etc/supervisord-devtools.conf")
  funcall-interactively(chezmoi-ediff "~/.local/etc/supervisord-devtools.conf")
  call-interactively(chezmoi-ediff record nil)
  command-execute(chezmoi-ediff record)
  execute-extended-command(nil "chezmoi-ediff" nil)
  funcall-interactively(execute-extended-command nil "chezmoi-ediff" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

I can't actually figure out why this is happening, but I am completely unable to `chezmoi-ediff` any file.

`GNU Emacs 28.0.91 (build 1, x86_64-apple-darwin21.2.0, NS appkit-2113.20 Version 12.1 (Build 21C52)) of 2022-01-13`

I'm happy to add any info that might help here, or try out possible fixes.

**Comment by offbyone** [comment]
I think I've narrowed it down a bit: it seems to happen only when I have changes in _subdirectories_, not in the top level.

**Comment by tuh8888** [comment]
Can you run `chezmoi target-file <file>` and `chezmoi source-file <file>` on the offending source and target file paths respectively and also verify that `chezmoi status` looks correct? Just to make sure that this isn't a `chezmoi` issue. 

Then, see in emacs try `(chezmoi-target <file>)` and `(chezmoi-source <file>)` (again for source and target offending file paths respectively). Then finally `(chezmoi-find <file>)` for both source file and target file paths.

Please report back what you get and if that is what you would expect given the structure of your system, install location of chezmoi, any nils, etc.

If you need a quick fix while we narrow down the culprits, try (note untested):
```emacs
(defun temp-chezmoi-ediff ()
   (interactive)
   (let* ((source (buffer-file-name))
             (target (shell-command-to-string (format "chezmoi target-file %s" source)))
       (ediff source target))
       (

```

**Comment by offbyone** [comment]
```
$ chezmoi target-file ~/.local/share/chezmoi/private_dot_local/etc/supervisord-devtools.conf.tmpl
chezmoi: unknown command "target-file" for "chezmoi"
```

I think I might have figured it out, now :) My guess is that chezmoi version I have is too old.

**Comment by offbyone** [comment]
```
❯ chezmoi source-path ~/.local/etc/supervisord-devtools.conf.tmpl
chezmoi: /Users/offby1/.local/etc/supervisord-devtools.conf.tmpl: not in source state

❯ chezmoi source-file ~/.local/etc/supervisord-devtools.conf.tmpl
chezmoi: unknown command "source-file" for "chezmoi"

❯ chezmoi target-path ~/.local/share/chezmoi/private_dot_local/etc/supervisord-devtools.conf.tmpl
chezmoi: unknown command "target-path" for "chezmoi"
```

**Comment by offbyone** [comment]
I had previously had 2.9.5, once I upgrade to 2.15.0 this now works. I'll leave it open if you want to track it for version detection, but I'm sorted now.

**Comment by tuh8888** [comment]
Sorry about giving you the wrong command. Yes, `target-path` was implemented by chezmoi to help this package work and was in version 2.12.0. In theory, I had a check to provide limited support users of older versions that don't have `chezmoi target-path`, but I guess that must not be working properly.
