### ISSUE TITLE
Feature request: Corfu integration

### ISSUE THREAD

**Issue by jgarte** [tuh8888/chezmoi.el#18]
This might be more a request to test [corfu](https://github.com/minad/corfu) and see make a checklist for what's needed for `chezmoi.el` integration.

**Comment by tuh8888** [comment]
I've been meaning to try corfu for my own Emacs setup, so I'll happily take a look when I get a chance.

**Comment by tuh8888** [comment]
I've been loving corfu, so I finally got around to writing a capf for chezmoi. See #25.

**Comment by jgarte** [comment]
I started using `guix home` for my dots: https://git.sr.ht/~whereiseveryone/confetti/tree/gnome/item/home.scm
