### ISSUE TITLE
Error when using onepassword from chezmoi - no files found

### ISSUE THREAD

**Issue by offbyone** [tuh8888/chezmoi.el#21]
I've got an issue with trying to use chezmoi inside emacs, where it isn't able to get a password into the underlying `op` command line:

```
Enter the password for 1password@offby1.net at my.1password.com: [ERROR] 2022/09/22 15:38:49 operation not supported by device
chezmoi: template: github-token:1:4: executing "github-token" at <onepasswordItemFields "Github">: error calling onepasswordItemFields: /usr/local/bin/op signin --raw: exit status 1
```

**Comment by tuh8888** [comment]
I'm not familiar enough with onepassword to offer a complete solution. With Bitwarden, rbw can be used as essentially a daemon for unlocking the vault (see the comments in this thread https://github.com/tuh8888/chezmoi.el/issues/6#issuecomment-1035529678). Perhaps there is a way to use gpg, daemon, or other mechanism to use onepassword without needing to provide a password to the subprocess.

**Comment by tuh8888** [comment]
Closing because interacting with subprocesses is hard. I still don't have a good general solution here.
