### ISSUE TITLE
'chezmoi-open-other' not respecting .chezmoiroot

### ISSUE THREAD

**Issue by ethanmoss1** [tuh8888/chezmoi.el#26]
Not sure if this effects anything else but when .chezmoiroot is set to anything other than than default it opens a file at the wrong location.

to reproduce;
initalise a repo in the default location (~/.local/share/chezmoi/) 
add .chezmoiroot file with the a new root location 
add a file to (eg alacritty) chezmoi
edit file with emacs in chezmoi and 'M-x chezmoi-open-other'
file will open with the .chezmoiroot as a prefix to the path.

```
echo 'home' > ~/.local/share/chezmoi/.chezmoiroot
chezmoi add ~/.config/alacritty/alacritty.yml
chezmoi edit

# in emacs, open alacritty file which will be located under the new root 'home'
M-x chezmoi-open-other
# it opens a file at location ~/home/.config/alacritty/alacritty.yml
```
showing the location it opens with the other file function:
![Screenshot_2023-02-07_14-35-03](https://user-images.githubusercontent.com/74180458/217275889-4f893006-e985-40af-838f-61740db6e685.png)

showing the location in the repo chezmoi uses
![Screenshot_2023-02-07_14-35-37](https://user-images.githubusercontent.com/74180458/217275893-b7d59811-ce8d-4a5d-947a-6bd774394b3f.png)

showing the new root location change by the .chezmoiroot file.
![Screenshot_2023-02-07_14-42-28](https://user-images.githubusercontent.com/74180458/217276298-b2b978ed-2ea0-4801-b968-ba368a9ecca0.png)

**Comment by tuh8888** [comment]
This might be a question for `chezmoi` itself. I just use `chezmoi target-path <source-file>` to find the actual file. I'm not that familiar with this feature. Where do you expect to find the file?
![harrison-desktop-lin-2023-02-07-1675808339_screenshot_752x197](https://user-images.githubusercontent.com/13961671/217379278-f7da8edb-ba6e-48f7-a65f-eaa5c8890e44.jpg)

**Comment by ethanmoss1** [comment]
You are right it seems, target-file should find the file at (using alacritty example) 
`~/.config/alacritty/alacritty.yml` but the command doesn't seem the check .chezmoiroot and trys to find the file at `~/home/.config/alacritty/alacritty.yml` 

It's interesting that `chezmoi source-file` is able to find the file with the changed chezmoi root. 

I'll open a issue with chezmoi. Thanks!

**Comment by ethanmoss1** [comment]
Apologies this has been left open so long, the issue has been fixed upstream.
