### ISSUE TITLE
`run_*` scripts not showing in `chezmoi-find`

### ISSUE THREAD

**Issue by shirdekel** [tuh8888/chezmoi.el#6]
Thanks for making this!

I have `run_once_` and `run_onchange_` scripts that I'd like access to through `chezmoi-find`, but at the moment they don't seem to show up so I have to navigate to them manually. Is this simply a feature that has not yet been implemented or should I look further into my setup?

**Comment by tuh8888** [comment]
I just realized those are chezmoi source state attributes you were referring too. At the moment, `chezmoi-find` presents the target file name to you, so you can't use it to search by parts of the name specific to the source state, namely the attributes that prefix them. You should be able to navigate to those files by their target filenames, but I understand if it would be useful to search by source state filename. I can implement a function like `chezmoi-find-source-file` if that would be useful to you. It's not a feature I think I'd use myself though, so if you could describe exactly how you'd like it to work, I can implement it for you.

**Comment by shirdekel** [comment]
Something like `chezmoi-find-source-file` would be great if those files can't be added to the normal `chezmoi-find`. The files I'm interested in are in `chezmoi cd`, but not in `chezmoi managed`. 

I actually find that I edit those files even more often than the normal dotfiles. I use them for updating a Brewfile and for changing macOS defaults, and I'm sure others would have that need too.

**Comment by tuh8888** [comment]
Reflecting on my own usage, I use a `.chezmoidata.json` file for managing chezmoi's variables, a file which isn't in `chezmoi managed`. When I want to access it, I actually use projectile's find file functionality since my chezmoi directory is a projectile project. I switch to my `~/.local/share/chezmoi` project (`projectile-switch-project`), and then look for the file I wand to edit by chezmoi source state name (`projectile-find-file`). I think this has functionality that I don't want to replicate myself, such as providing only files not ignored by git. If you use projectile, would this work flow satisfy what you're looking for?

For a quick and dirty function that could do this (untested since I'm not in front of my config right now):
```elisp
(defun chezmoi-projectile-find-file ()
  (interactive)
  (projectile-switch-project "~/.local/share/chezmoi")
  (call-interactively #'projectile-find-file))

(bind-key (kbd "C-c C-f") #'chezmoi-projectile-find-file)
```

**Comment by shirdekel** [comment]
Yes that's exactly what I do at the moment. But how do you do the subsequent `chezmoi apply`? I'm trying to cut out the step of opening a terminal buffer and entering that in.

**Comment by shirdekel** [comment]
Yeah that looks good. Except I also have a need to sometimes enter a password (because I use chezmoi with Bitwarden). Is there a way to handle that through the the emacs prompt rather than the shell?

**Comment by gwbrck** [comment]
When it comes to Bitwarden, I can recommend some functions from [emacs-bitwarden](https://github.com/seanfarley/emacs-bitwarden/blob/main/bitwarden.el). For me this works fine: 
```elisp
  (defun bitwarden-unlock ()
    "Minimal version of https://github.com/seanfarley/emacs-bitwarden"
    (interactive)
    (let* ((bws (shell-command-to-string
                 (concat (executable-find "bw") " status")))
           (cmd (cond ((string-match "unauthenticated" bws)  "login")
                      ((string-match "locked" bws)  "unlock")
                      ((string-match "unlocked" bws) nil))))
      (when cmd
        (when (get-process "bitwarden")
          (delete-process "bitwarden"))
        (make-process :name "bitwarden"
                      :buffer nil
                      :connection-type 'pipe
                      :command (list (executable-find "bw") cmd)
                      :filter #'bitwarden--proc-filter))))

  (defun bitwarden--proc-filter (proc string)
    "Interacts with PROC by sending line-by-line STRING."
    (when (string-match "^? Email address:" string)
      (process-send-string proc (concat (read-string "Bitwarden email: ") "\n")))
    (when (string-match "^? Master password:" string)
      (process-send-string
       proc (concat (read-passwd "Bitwarden master password: ") "\n")))
    (when (string-match "^Username or password is incorrect" string)
      (message "incorrect master password"))
    (when (string-match "^You are not logged in" string)
      (message "cannot unlock: not logged in"))
    (when (string-match "^? Two-step login code:" string)
      (process-send-string
       proc (concat (read-passwd "Bitwarden two-step login code: ") "\n")))
    (when (string-match "^Login failed" string)
      (message "incorrect two-step code"))
    (when (string-match "^You are already logged in" string)
      (string-match "You are already logged in as \\(.*\\)\\." string)
      (message "already logged in as %s" (match-string 1 string)))
    (when (string-match "^\\(You are logged in\\|Your vault is now unlocked\\)"
                        string)
      (string-match "export BW_SESSION=\"\\(.*\\)\"" string)
      (setenv "BW_SESSION" (match-string 1 string))
      (message "successfully logged in.")))
```

**Comment by tuh8888** [comment]
The most recent commit should address this without any of the new functions we discussed being needed. From within any file in the chezmoi source directory, use `M-x chezmoi-write` to apply changes using that source file. My basic tests using a `run_once` file seemed to show the expected changes in the target state. Give it a try and let me know if it is behaving as you'd hope.

**Comment by shirdekel** [comment]
Thanks! Only issue I have now is that sometimes it looks like I need to interact with the terminal. For instance, to test this I changed my `run_once_before_` script (which is mostly a Brewfile) to download a new package and I got the following:

```
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
```

Running `chezmoi apply` from a shell just asks me for a password and installs as normal.

**Comment by tuh8888** [comment]
Turns out handling input from shell commands through emacs is tricky. `chezmoi-write` now accepts a prefix argument which just opens a shell buffer which runs the apply command, which should allow for any input your chezmoi command asks for (sudo, bitwarden, etc.). I believe leaving this shell buffer open will mean that each time you issue `chezoi-write` with the prefix argument, it should re-use the running shell so you won't have to repeatedly input passwords. Let me know if this is an acceptable solution.

**Comment by shirdekel** [comment]
Great, thanks! The only thing that is still surprising is that `chezmoi-projectile-find-file` asks me for input twice: once for a "pattern", and again for "Find file". I would expect to only be asked once. For instance, when I manually do `helm-projectile-switch-project` and select `~/.local/share/chezmoi`, I get asked for a "pattern", select the file I want, and then it switches to it, while eliminating the helm buffer.

**Comment by tuh8888** [comment]
You're welcome! Regarding `chezmoi-projectile-find-file`, that was just an off-the-cuff function I thought might help speed up your workflow and won't become part of `chezmoi.el`. It's up to you to tune that function to work for your needs, and I didn't test it earlier. That said, this should only ask for a file once:
```elisp
(defun chezmoi-projectile-find-file ()
  (interactive)
  (projectile-switch-project-by-name  "~/.local/share/chezmoi")
  ;; Not need if projectile-switch-project-action is set to projectile-find-file
  ;;(call-interactively #'projectile-find-file)
)
```

**Comment by shirdekel** [comment]
True, that was quite simple. Thanks for taking to time to help!

**Comment by tuh8888** [comment]
Closing this. Can re-open if, after using the fixes, you decide you are still not satisfied with the workflow.
